// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjrliUcwIez2UcIU2CsVvURWrCIa3PpHk',
    appId: '1:176790922353:web:75eaef76e110237f64a7d0',
    messagingSenderId: '176790922353',
    projectId: 'satnusa',
    authDomain: 'satnusa.firebaseapp.com',
    storageBucket: 'satnusa.firebasestorage.app',
    measurementId: 'G-35SBLBKVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAB0myrfMhCFPCW6yZ8aHLljicryOeurA',
    appId: '1:176790922353:android:46af902fdcb8f7c564a7d0',
    messagingSenderId: '176790922353',
    projectId: 'satnusa',
    storageBucket: 'satnusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHRsFlJoQUYTT4WW73qbcrDQEeIjXFsA',
    appId: '1:176790922353:ios:cf8ff2a72cbaa56064a7d0',
    messagingSenderId: '176790922353',
    projectId: 'satnusa',
    storageBucket: 'satnusa.firebasestorage.app',
    iosBundleId: 'com.example.satnusaTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHRsFlJoQUYTT4WW73qbcrDQEeIjXFsA',
    appId: '1:176790922353:ios:cf8ff2a72cbaa56064a7d0',
    messagingSenderId: '176790922353',
    projectId: 'satnusa',
    storageBucket: 'satnusa.firebasestorage.app',
    iosBundleId: 'com.example.satnusaTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjrliUcwIez2UcIU2CsVvURWrCIa3PpHk',
    appId: '1:176790922353:web:57cf6a51d947f0de64a7d0',
    messagingSenderId: '176790922353',
    projectId: 'satnusa',
    authDomain: 'satnusa.firebaseapp.com',
    storageBucket: 'satnusa.firebasestorage.app',
    measurementId: 'G-RNC9WMZ6KV',
  );
}
